/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CredentialStoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "credentials"
      | "issueCredential"
      | "registry"
      | "revokeCredential"
      | "verifyCredential"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CredentialIssued" | "CredentialRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "credentials",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCredential",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCredential",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "credentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCredential",
    data: BytesLike
  ): Result;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    issuer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contentHash: string,
    issuer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    contentHash: string;
    issuer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [contentHash: BytesLike, issuer: AddressLike];
  export type OutputTuple = [contentHash: string, issuer: string];
  export interface OutputObject {
    contentHash: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CredentialStore extends BaseContract {
  connect(runner?: ContractRunner | null): CredentialStore;
  waitForDeployment(): Promise<this>;

  interface: CredentialStoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  credentials: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean] & {
        issuer: string;
        contentHash: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;

  issueCredential: TypedContractMethod<
    [_hash: BytesLike],
    [void],
    "nonpayable"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  revokeCredential: TypedContractMethod<
    [_hash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyCredential: TypedContractMethod<
    [_hash: BytesLike],
    [[boolean, string, bigint]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "credentials"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean] & {
        issuer: string;
        contentHash: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueCredential"
  ): TypedContractMethod<[_hash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<[_hash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyCredential"
  ): TypedContractMethod<
    [_hash: BytesLike],
    [[boolean, string, bigint]],
    "view"
  >;

  getEvent(
    key: "CredentialIssued"
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;

  filters: {
    "CredentialIssued(bytes32,address,uint256)": TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    "CredentialRevoked(bytes32,address)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
  };
}
