/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IssuerRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveIssuer"
      | "isIssuer"
      | "issuers"
      | "owner"
      | "registerIssuer"
      | "revokeIssuer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IssuerApproved"
      | "IssuerRegistered"
      | "IssuerRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerIssuer",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeIssuer",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isIssuer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "issuers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeIssuer",
    data: BytesLike
  ): Result;
}

export namespace IssuerApprovedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRegisteredEvent {
  export type InputTuple = [issuer: AddressLike, name: string];
  export type OutputTuple = [issuer: string, name: string];
  export interface OutputObject {
    issuer: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRevokedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IssuerRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IssuerRegistry;
  waitForDeployment(): Promise<this>;

  interface: IssuerRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveIssuer: TypedContractMethod<
    [_issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  isIssuer: TypedContractMethod<[_issuer: AddressLike], [boolean], "view">;

  issuers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        domain: string;
        isApproved: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerIssuer: TypedContractMethod<
    [_name: string, _domain: string],
    [void],
    "nonpayable"
  >;

  revokeIssuer: TypedContractMethod<
    [_issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveIssuer"
  ): TypedContractMethod<[_issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isIssuer"
  ): TypedContractMethod<[_issuer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issuers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        domain: string;
        isApproved: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerIssuer"
  ): TypedContractMethod<
    [_name: string, _domain: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeIssuer"
  ): TypedContractMethod<[_issuer: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "IssuerApproved"
  ): TypedContractEvent<
    IssuerApprovedEvent.InputTuple,
    IssuerApprovedEvent.OutputTuple,
    IssuerApprovedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRegistered"
  ): TypedContractEvent<
    IssuerRegisteredEvent.InputTuple,
    IssuerRegisteredEvent.OutputTuple,
    IssuerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRevoked"
  ): TypedContractEvent<
    IssuerRevokedEvent.InputTuple,
    IssuerRevokedEvent.OutputTuple,
    IssuerRevokedEvent.OutputObject
  >;

  filters: {
    "IssuerApproved(address)": TypedContractEvent<
      IssuerApprovedEvent.InputTuple,
      IssuerApprovedEvent.OutputTuple,
      IssuerApprovedEvent.OutputObject
    >;
    IssuerApproved: TypedContractEvent<
      IssuerApprovedEvent.InputTuple,
      IssuerApprovedEvent.OutputTuple,
      IssuerApprovedEvent.OutputObject
    >;

    "IssuerRegistered(address,string)": TypedContractEvent<
      IssuerRegisteredEvent.InputTuple,
      IssuerRegisteredEvent.OutputTuple,
      IssuerRegisteredEvent.OutputObject
    >;
    IssuerRegistered: TypedContractEvent<
      IssuerRegisteredEvent.InputTuple,
      IssuerRegisteredEvent.OutputTuple,
      IssuerRegisteredEvent.OutputObject
    >;

    "IssuerRevoked(address)": TypedContractEvent<
      IssuerRevokedEvent.InputTuple,
      IssuerRevokedEvent.OutputTuple,
      IssuerRevokedEvent.OutputObject
    >;
    IssuerRevoked: TypedContractEvent<
      IssuerRevokedEvent.InputTuple,
      IssuerRevokedEvent.OutputTuple,
      IssuerRevokedEvent.OutputObject
    >;
  };
}
